#!/bin/bash
#===============================================================================
# FastNodeUbuntu — Configuration
# Ubuntu 24 LTS
#===============================================================================

INTERACTIVE_MODE="true"

# SSH
SSH_PORT="2225"
SSH_PERMIT_ROOT="yes"
SSH_PASSWORD_AUTH="no"
SSH_EMPTY_PASSWORDS="no"
# Оставьте пустым — ключ будет запрошен интерактивно при запуске модуля 04
# Или задайте здесь для автоматического режима:
SSH_PUBLIC_KEY=""

# SWAP
SWAP_SIZE="2G"
SWAP_FILE="/swapfile"
SWAP_SWAPPINESS="80"

# Network
DISABLE_IPV6="true"
ALLOWED_PORTS=("2225" "80" "443" "8443" "2096")

# Fail2Ban
FAIL2BAN_MAXRETRY="5"
FAIL2BAN_FINDTIME="3600"
FAIL2BAN_BANTIME="86400"
FAIL2BAN_IGNORE_IPS=("127.0.0.1/8" "::1")

# External Scripts
EXTERNAL_SCRIPTS=(
    "https://raw.githubusercontent.com/FuriousWarrior/FuriousTrafficGuard/refs/heads/main/install-trafficguard.sh"
    "https://raw.githubusercontent.com/begugla0/remnawave-node-scripts/main/remnanode-install.sh"
    "https://gitflic.ru/project/furiouswarrior/furious-motd/blob/raw?file=install-motd.sh"
)

# Packages (module 07)
REQUIRED_PACKAGES=(
    "mc" "htop" "screen" "build-essential" "python3-pip" "gnupg2" "logrotate"
    "sudo" "tmux" "ncdu" "grc" "glances" "curl" "ufw" "fail2ban"
    "chrony" "locales" "openssh-server"
)

# Locale
LOCALE_LANG="ru_RU.UTF-8"
LOCALE_CHARSET="UTF-8"

# Timezone
TIMEZONE="Europe/Moscow"
